# permissions for end users to edit units.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: unit-editor-role
rules:
- apiGroups:
  - custom.hmlss.ml
  resources:
  - units
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - custom.hmlss.ml
  resources:
  - units/status
  verbs:
  - get
